anitab-org/open-source-day

code_of_conduct.md, reporting_guidelines.md
- Add a copy of code of conduct from https://github.com/anitab-org/mentorship-backend/blob/develop/docs/code_of_conduct.md with changes to the email address used.
- Add a copy of reporting guidelines from https://github.com/anitab-org/mentorship-backend/blob/develop/docs/reporting_guidelines.md with changes to the email address used.
note: code of conduct references reporting guidelines
=> Add code of conduct and reporting guidelines

_pages/become_a_mentor.md
Update the "Become a mentor" page with relevant information.
Used codespaces to build the website and test it.
=> Updated become a mentor page

_pages/open-source-day-2021-summer-contribution.md
- Add featured and choose your own adventure projects
=> Add feature and choose your own adventure projects

_site/index.html
Fixes #4 
Fixes #2 
Fixed the tag for the links to open in a new tab.
=> Minor change in index file for Issue 2 and 4

_pages/open-source-day-2021-summer-learning.md
Updated Security 101 talk description.
=> Add workshop info

_pages/become_a_mentor.md
added the list of projects to become a mentor information page
Yes, using codespaces
=> added the list of projects to become a mentor information page

_pages/open-source-day-2021-summer-learning.md
Fixed images path by adding /open-source-day to the url.
=> fixed images path

assets/css/main.scss
Updated color schema of mentor card to match event.
- Code
Using codespaces
=> Updated color schema to match event

_includes/mentor-profile.html
=> revert mentors images path to work on main

_includes/mentor-profile.html
Hopefully this will fix the image url.
=> fixing imgaes url

_data/mentors-directory.yaml
Added more information for mentor Madhurima
Reviewed mentor information
=> Updated information for Mentor

_data/mentors-directory.yaml
Modified entry for Ashpan on Mentor Directory
=> Updated mentor directory entry for Ashpan

_data/mentors-directory.yaml
=> updated opensuse mentor

_data/mentors-directory.yaml, _data/workshops.yaml
Workshop description fix and mentors slack links
=> Workshop description fix and mentors slack links

_pages/become_a_mentor.md
updated mentors application to standby for now
=> updated mentors application to standby for now

_pages/become_a_mentor.md
Embedded the new mentors application form and list of available projects for vGHC attendees to join.
=> updated with new mentors application form

_pages/become_a_mentor.md
reopened mentors application and updated to the new process
=> reopened mentors application and updated to the new process

_data/projects/openeducation-2021.yaml, _data/projects/rowy-2021.yaml
Updated projects with new names.
=> renamed projects

_data/projects/wildflyelytron-2021.yaml
Updated my mentor info slack url for Wildfly Elytron 
=> Updated Ashpan's slack url

_data/projects/a11y-2021.yaml
=> added spaces to yaml

_data/projects/apacheshardingsphere-2021.yaml
=> Add mentor info- Shraddha Shaligram

_data/projects/greenpeace-2021.yaml, _data/projects/opensuse-2021.yaml
=> Changed the mentor listing to the assigned project (OpenSUSE to Greenpeace)

_data/projects/greenpeace-2021.yaml
Add Kriti Singh to greenpeace mentors directory
=> Add Kriti Singh to greenpeace mentors directory

Gemfile, Gemfile.lock, README.md, _config.yml, docker/Dockerfile, docker/docker-compose.yaml
Provide container based build and debug option for the site.
Fixes N/A
- Code
=> Container build and serve debug option

_data/projects/qairamap-2021.yaml
Add Yogita Bhatia under qAIRaMap project directory
=> Add mentors info for qAIRaMap project for vGHC OSD

_pages/open-source-day-2021-GHC-contribution.md
- Modify github issue link for Spring Boot
- Add missing maintainers
- Modify description for FireFly
=> Modify project description and maintainers

_data/projects/openeducation-2021.yaml
Added mentor information for OpenEducation - 2021
=> Added mentor information for OpenEducation - 2021

_data/projects/a11y-2021.yaml
Corrects misspelling of Santina's name
NA
=> corrects spelling error

_pages/open-source-day-2021-GHC-contribution.md
- Move FireFly project under Hyperledger
- Fix broken links for project FireFly
- Fix broken links for project Rowy
=> Move FireFly project under Hyperledger

_pages/open-source-day-2021-GHC-contribution.md
Fix broken link for OpenStreeMap project
=> Fix broken link for openstreetmap

_pages/choose-your-own-adventure.md
CYOA projects have been added the webpage.
=> Added CYOA info

_pages/featured-projects.md
=> Adding feature project info

_pages/learning-track.md
Add workshop details to the learning track section of the open source day website
Adding content
- Code
- Outreach
This has been tested locally by running the jekyll project on my local machine and viewing the result of the browser.
- [X ] I have made corresponding changes to the documentation
- [] Any dependent changes have been merged
=> Add learning track workshop details

_data/agenda.yml, _pages/agenda.md, assets/css/agenda.css
Add agenda summary page
- Manual/ ad-hoc testing in the local environment
=> feat: add osd 22 agenda summary page

assets/css/committee.css
=> fix: mobile view styling

_pages/featured.md
from nodejs/nodejs.org to nodejs/node
nodejs.org is just the website, so we should be using "node" which is which is the main repo. The issues link point to this repo as well.
=> Fix project link for nodejs

_pages/workshops.md
It's "The Open Source Game" - removed the "s"
- Code
- Outreach
=> fixed type on workshop

_pages/faq.md
=> Adding cyoa faq

_pages/news.md
Include new Blog from NearForm on News page ("At NearForm, the Future is Open")
- Outreach
- Pull request for this as requested on team Slack
Sync'd fork from upstream, made change locally, built and tested locally.
Screen shot of the new News page including the new blog is attached
=> paulapaul | include new Blog from NearForm on News page

_data/mentors.yml
Update mentors.yml with mentor's GitHub information.
=> Update mentor information with github information

_data/cyoa-projects.yml
=> Updating links for data profiler
